name: LuaInMinecraftBukkit
main: tk.smileyik.luainminecraftbukkit.LuaInMinecraftBukkit
version: 1.1-SNAPSHOT
author: SmileYik
commands:
  lua:
    permission: LuaInMinecraftBukkit.Admin
  luap:
permissions:
  LuaInMinecraftBukkit.Admin:
    default: op